# Generated by Django 5.2.7 on 2025-10-21 21:41

import config.utils
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDActivity',
            fields=[
                ('id', config.utils.CustomShortUUIDField(editable=False, max_length=31, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for the activity.', null=True, upload_to='cpd_activities/thumbnails/')),
                ('link', models.URLField(blank=True, help_text='Link to the activity details or registration page.', max_length=500, null=True)),
                ('provider', models.CharField(blank=True, help_text='Provider of the activity, if applicable.', max_length=255)),
                ('activity_type', models.CharField(choices=[('course', 'Course'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('conference', 'Conference'), ('certification', 'Certification'), ('self_study', 'Self Study'), ('mentoring', 'Mentoring'), ('research', 'Research'), ('other', 'Other')], default='other', help_text='Category of activity for program-specific rule application', max_length=20)),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Start date and time of the activity, if applicable.', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, help_text='End date and time of the activity, if applicable.', null=True)),
                ('default_points_per_hour', models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Default points awarded per hour for this activity', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Approval status of the CPD activity', max_length=20)),
                ('is_manual', models.BooleanField(default=False, help_text='Indicates if this activity is manually professional user.')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the activity was approved.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the activity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the activity was last updated.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cpd_activities', to=settings.AUTH_USER_MODEL)),
                ('recommended_professions', models.ManyToManyField(blank=True, help_text='Professions for which this activity is recommended.', related_name='recommended_cpd_activities', to='users.profession')),
            ],
            options={
                'verbose_name': 'CPD Activity',
                'verbose_name_plural': 'CPD Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='idx_cpd_activity_title'), models.Index(fields=['provider'], name='cpd_activit_provide_b5e9bd_idx')],
            },
        ),
    ]
