# Generated by Django 5.2.7 on 2025-10-21 21:41

import config.utils
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpd_activities', '0001_initial'),
        ('cpd_managements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDLogEntry',
            fields=[
                ('id', config.utils.CustomShortUUIDField(editable=False, max_length=31, primary_key=True, serialize=False, unique=True)),
                ('is_manual', models.BooleanField(default=True, help_text='Whether this is a manual entry (True) or catalog activity (False)')),
                ('activity_type', models.CharField(choices=[('course', 'Course'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('conference', 'Conference'), ('certification', 'Certification'), ('self_study', 'Self Study'), ('mentoring', 'Mentoring'), ('research', 'Research'), ('other', 'Other')], default='other', help_text='Type/category of the CPD activity', max_length=20)),
                ('manual_title', models.CharField(blank=True, help_text='Title for manual entries (not used for catalog activities)', max_length=200, null=True)),
                ('manual_description', models.TextField(blank=True, help_text='Description for manual entries (not used for catalog activities)', null=True)),
                ('manual_provider', models.CharField(blank=True, help_text='Provider for manual entries (not used for catalog activities)', max_length=200, null=True)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Total hours spent on the CPD activity.', max_digits=5)),
                ('completed_at', models.DateField(help_text='Date the CPD activity was completed.')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Start date and time of the activity', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, help_text='End date and time of the activity', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or reflections by the user.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpd_activity', models.ForeignKey(blank=True, help_text='Link to a pre-defined catalog activity (null for manual entries)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='cpd_activities.cpdactivity')),
                ('user', models.ForeignKey(help_text='The professional user who logged this activity.', on_delete=django.db.models.deletion.CASCADE, related_name='cpd_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CPD Log Entry',
                'verbose_name_plural': 'CPD Log Entries',
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CPDLogDetails',
            fields=[
                ('id', config.utils.CustomShortUUIDField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('program_category_code', models.CharField(blank=True, help_text='Legacy field - kept for backward compatibility, use program_category instead', max_length=50, null=True)),
                ('points_per_hour', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Points awarded per hour based on program criteria', max_digits=5)),
                ('total_points', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Total points calculated for this program', max_digits=6)),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Hours counted towards this program (may be capped)', max_digits=5)),
                ('validated_at', models.DateTimeField(blank=True, help_text='When this entry was validated for the program', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_criteria', models.ForeignKey(blank=True, help_text='The credential criteria used for points calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_log_details', to='cpd_managements.credentialcriteria')),
                ('enrollment', models.ForeignKey(help_text="The user's program enrollment cycle this activity applies to", on_delete=django.db.models.deletion.CASCADE, related_name='log_details', to='cpd_managements.enrollment')),
                ('program_category', models.ForeignKey(blank=True, help_text='The program-specific category selected for this activity (replaces program_category_code)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_log_details', to='cpd_managements.credentialcriteria')),
                ('log_entry', models.ForeignKey(help_text='The CPD log entry', on_delete=django.db.models.deletion.CASCADE, related_name='log_details', to='cpd_tracking.cpdlogentry')),
            ],
            options={
                'verbose_name': 'CPD Log Detail',
                'verbose_name_plural': 'CPD Log Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', config.utils.CustomShortUUIDField(editable=False, max_length=31, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('file', 'File Upload'), ('url', 'URL Link')], default='file', help_text='Type of evidence provided for the CPD activity.', max_length=50)),
                ('file', models.FileField(blank=True, help_text='Uploaded evidence file (e.g., certificate).', null=True, upload_to='cpd_evidence/')),
                ('url', models.URLField(blank=True, help_text='URL to online evidence (e.g., certificate link).', max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the evidence was uploaded.')),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cpd_tracking.cpdlogentry')),
            ],
            options={
                'verbose_name': 'CPD Evidence',
                'verbose_name_plural': 'CPD Evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cpdlogentry',
            index=models.Index(fields=['completed_at'], name='cpd_trackin_complet_d68037_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdlogentry',
            index=models.Index(fields=['is_manual'], name='cpd_trackin_is_manu_e159b4_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdlogentry',
            index=models.Index(fields=['activity_type'], name='cpd_trackin_activit_50e0f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cpdlogentry',
            unique_together={('user', 'cpd_activity', 'completed_at')},
        ),
        migrations.AddIndex(
            model_name='cpdlogdetails',
            index=models.Index(fields=['enrollment'], name='cpd_trackin_enrollm_7f965e_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdlogdetails',
            index=models.Index(fields=['log_entry'], name='cpd_trackin_log_ent_4ad06d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cpdlogdetails',
            unique_together={('log_entry', 'enrollment')},
        ),
    ]
