# Generated by Django 5.2.7 on 2025-10-21 21:41

import config.utils
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialingProgram',
            fields=[
                ('id', config.utils.CustomShortUUIDField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name of the credentialing program. Do not abbreviate or use acronyms.', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='URL-friendly version of the program name, auto-generated from the name field.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(help_text='Name of the organization providing the credentialing program. Do not abbreviate or use acronyms.', max_length=255)),
                ('renewal_period_months', models.PositiveIntegerField(default=12, help_text='Renewal interval, in months (e.g. 3 for quarterly, 6 for semi-annual, 10 for every 10 months).')),
                ('methodology', models.CharField(choices=[('hours_based', 'Hours Based'), ('points_based', 'Points Based'), ('hybrid', 'Hybrid (Hours and Points)')], default='points_based', help_text='Methodology used for CPD requirements.', max_length=20)),
                ('required_points', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Total points required for the credentialing program.', max_digits=6)),
                ('required_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Total hours required for the credentialing program.', max_digits=6)),
                ('allow_carryover', models.BooleanField(default=False, help_text='Allow carryover of unused hours/points to the next cycle')),
                ('max_carryover_points', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum carryover points allowed.', max_digits=5, null=True)),
                ('max_carryover_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum carryover hours allowed.', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', help_text='Status of the credentialing program. Draft/Archived programs are not visible to users.', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credentialing Program',
                'verbose_name_plural': 'Credentialing Programs',
                'ordering': ['name'],
                'unique_together': {('name', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='CredentialCriteria',
            fields=[
                ('id', config.utils.CustomShortUUIDField(editable=False, max_length=27, primary_key=True, serialize=False, unique=True)),
                ('category_code', models.CharField(default='other', help_text="Unique code/identifier for this category within the program (e.g., '1', '2', 'course', 'formal_ed')", max_length=50)),
                ('category_name', models.CharField(default='Other Activity', help_text="Display name for this category (e.g., 'Formal education and training', 'Short courses')", max_length=200)),
                ('category_description', models.TextField(blank=True, help_text='Detailed description of what activities fall under this category', null=True)),
                ('points_per_hour', models.DecimalField(decimal_places=1, default=Decimal('0.00'), help_text='Points awarded per hour of activity in this category.', max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which this category should be displayed')),
                ('program', models.ForeignKey(help_text='The credentialing program this criteria belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='cpd_managements.credentialingprogram')),
            ],
            options={
                'verbose_name': 'Program Category Rule',
                'verbose_name_plural': 'Program Category Rules',
                'ordering': ['sort_order', 'category_code'],
                'unique_together': {('program', 'category_code')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', config.utils.CustomShortUUIDField(editable=False, max_length=29, primary_key=True, serialize=False, unique=True)),
                ('cycle_start_date', models.DateField(help_text='Start date of this enrollment cycle. Cannot be in the future.')),
                ('cycle_end_date', models.DateField(help_text='End date of this enrollment cycle')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', help_text='Current status of the enrollment cycle', max_length=20)),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the user enrolled in the program cycle')),
                ('accumulated_hours', models.DecimalField(decimal_places=1, default=0, help_text='Total approved hours accumulated in this cycle including carryover', max_digits=6)),
                ('accumulated_points', models.DecimalField(decimal_places=1, default=0, help_text='Total approved points accumulated in this cycle including carryover', max_digits=6)),
                ('applied_carryover_hours', models.DecimalField(decimal_places=1, default=0, help_text='Hours carried over from the previous cycle', max_digits=5)),
                ('applied_carryover_points', models.DecimalField(decimal_places=1, default=0, help_text='Points carried over from the previous cycle', max_digits=5)),
                ('program', models.ForeignKey(help_text='The credentialing program the user is enrolled in.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cpd_managements.credentialingprogram')),
                ('user', models.ForeignKey(help_text='The user enrolled in the credentialing program.', limit_choices_to={'role': 'professional'}, on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Program Enrollment',
                'verbose_name_plural': 'User Program Enrollments',
                'ordering': ['-cycle_start_date', 'user'],
                'unique_together': {('user', 'program', 'cycle_start_date')},
            },
        ),
    ]
